import { Box } from '@mui/material'
import React from 'react'
import Termstyle from '../Style/Termstyle'
import Footer from './Footer'
import Termlang from './Termlang'

function Privacy() {
    return (
        <>
            <Termstyle>
                <Box className='mterm'>
                    <Box className='maint'>
                        <Box className='policy'>
                            <h1>PRIVACY POLICY</h1>
                            <p>Last updated [September 06th, 2022]</p>
                            <p>Our Privacy Policy forms part of and must be read in conjunction with, the website and Mobile Application Terms and Conditions. We reserve the right to change this Privacy Policy at any time.</p>
                            <p>We respect the privacy of our users and every person who visits our site <a href='www.dentalcam.app'><strong>www.dentalcam.app</strong></a> and the Mobile Application “DentalCam”. Here Circonvallazione Sud 47 referred to as (“we”, “us”, or “our”), we are committed to protecting your personal information and your right to privacy under this Privacy policy. If you have any questions or concerns about our policy or our practices regarding your personal information, please contact us at <strong>info@dentalcam.app.</strong></p>
                            <p>When you visit our website <a href='www.dentalcam.app'><strong>www.dentalcam.app</strong></a> (“Site”) and Mobile Application (<strong>“DentalCam”</strong>) and use our services, you trust us with your personal information. We take your privacy very seriously. In this privacy notice, we describe our privacy policy. We seek to explain to you in the clearest way possible what information we collect, how we use it, and what rights you have concerning it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy policy that you do not agree with, please discontinue the use of our site and our services.</p>
                            <p>This privacy policy applies to all information collected through our website and mobile application, and/or any related services, sales, marketing, or events (we refer to them collectively in this privacy policy as the <strong>“Website and Mobile Application“</strong>).</p>
                            <p><strong>ABOUT US</strong></p>
                            <p>At the DentalCam app and website, we offer you a meticulously designed platform for dental services. This platform provides services to the Clinic and the patients.</p>
                            <p>We are located in Italy.</p>
                            <p><strong>Please read this privacy policy carefully as it will help you make informed decisions about sharing your personal information with us.</strong></p>
                            <ol>
                                <li>
                                    <h3>WHAT INFORMATION DO WE COLLECT?</h3>
                                    <p>The personal information you disclose to us</p>
                                    <p>We collect personal information that you voluntarily provide to us when expressing an interest in obtaining information about us or our services when participating in activities on the Website and Mobile Application or otherwise contacting us.</p>
                                    <p>We collect personal information that you voluntarily provide to us when expressing an interest in obtaining information about us or our services when participating in activities on the Website and Mobile Application or otherwise contacting us.</p>
                                    <p>The personal information that we collect depends on the context of your interactions with us and the Website and Mobile Application, the choices you make, and the features you use. The personal information we collect can include the following:</p>
                                    <p><strong>Name and Contact Data.</strong> We collect your first and last name, email address, phone number, medical issues, and other similar details.</p>
                                    <p><strong>Access.</strong> We will access the following once the user allows it through the app:</p>
                                    <ul>
                                        <li>Internet Access</li>
                                        <li>Background Services Access</li>
                                    </ul>
                                    <p><strong>Credentials.</strong> We collect passwords, password hints, and similar security information used for authentication and account access.</p>
                                    <p><strong>Information automatically collected</strong></p>
                                    <p>We automatically collect certain information when you visit, use, or navigate the Website and Mobile Application. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser, and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Website and Mobile Application and other technical information. If you access our site with your mobile device, we may automatically collect device information (such as your mobile device ID, model, and manufacturer), operating system, version information, and IP address. This information is primarily needed to maintain the security and operation of our Website and Mobile Application, and for our internal analytics and reporting purposes.</p>
                                    <p>Like many businesses, we also collect information through cookies and similar technologies. You can find out more about this in our Cookie Policy.</p>
                                    <p><strong>Information collected from other Sources</strong></p>
                                    <p>We may obtain information about you from other sources, such as public databases, joint marketing partners, social media platforms (such as Facebook), as well as from other third parties.</p>
                                    <p>If you have chosen to subscribe to our newsletter, your first name, last name and e-mail address will be shared with our newsletter provider. This is to keep you updated with information and offers for marketing purposes.</p>
                                </li>
                                <li><h3>HOW DO WE USE YOUR INFORMATION?</h3><p>We use your personal information for these purposes in reliance on our legitimate business interests (“Business Purposes”), to enter into or perform a contract with you (“Contractual”), with your consent (“Consent”), and/or for compliance with our legal obligations (“Legal Reasons”). We indicate the specific processing grounds we rely on next to each purpose listed below. </p><p>We use the information we collect or receive: </p><ul><li><strong>Deliver targeted advertising to you </strong>for our Business Purposes and/or with your Consent. We may use your information to develop and display content and advertising (and work with third parties who do so) tailored to your interests and/or location and to measure its effectiveness. [For more information, see our Cookie Policy.</li><li><strong>Request Feedback </strong>for our Business Purposes and/or with your Consent. We may use your information to request feedback and to contact you about your use of our Website and Mobile Application</li><li><strong>To protect our Website and Mobile Application </strong>for Business Purposes and/or Legal Reasons. We may use your information as part of our efforts to keep our Website and Mobile Application safe and secure (for example, for fraud monitoring and prevention).</li><li><strong>To enforce our terms, conditions, and policies </strong>for our business purposes and as legally required.</li><li><strong>To respond to legal requests and prevent harm </strong>as legally required. If we receive a subpoena or other legal request, we may need to inspect the data we hold to determine how to respond.</li><li><strong>For other Business Purposes </strong>We may use your information for other Business Purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Website and Mobile Application, products, services, marketing, and your experience.</li></ul></li>
                                <li><h3>WILL YOUR INFORMATION BE SHARED WITH ANYONE?</h3><p>We only share and disclose your information in the following situations:</p><ul><li><strong>Compliance with Laws. </strong>We may disclose your information where we are legally required to do so to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal processes, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</li><li><strong>Vital Interests and Legal Rights. </strong>We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.</li><li><strong>Vendors, Consultants, and Other Third-Party Service Providers. </strong>We may share your data with third-party vendors, service providers, contractors, or agents who perform services for us or on our behalf and require access to such information to do that work. </li><li><strong>Business Transfers. </strong>We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</li><li><strong>Third-Party Advertisers. </strong>We may use third-party advertising companies to serve ads when you visit the Website and Mobile Application. These companies may use information about your visits to our Website Mobile Application and other websites that are contained in web cookies and other tracking technologies to provide advertisements about goods and services of interest to you.</li><li><strong>Affiliates. </strong>We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy policy. Affiliates include our parent company and any subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.</li><li><strong>Business Partners. </strong>We may share your information with our business partners to offer you certain products, services, or promotions.</li><li><strong>With your Consent. </strong>We may disclose your personal information for any other purpose with your consent.</li><li><strong>Other Users. </strong>When you share personal information (for example, by posting comments, contributions, or other content to the Website and Mobile Application) or otherwise interact with public areas of the Website and Mobile Application, such personal information may be viewed by all users and may be publicly distributed outside the Website and Mobile Application in perpetuity.</li></ul></li>
                                <li><h3>DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</h3><p>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.</p></li>
                                <li><h3>IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</h3><p>Our platform server is located in Germany. Information collected from you may be stored and processed globally in various countries in which our Company or agents or contractors maintain facilities, and by accessing our sites and using our services, you consent to any such transfer of information outside of your country.</p><p>Such countries may have laws that are different, and potentially not as protective, as the laws of your own country. Whenever we share personal data originating in the European Economic Area we will rely on lawful measures to transfer that data, such as the Privacy Shield or the EU standard contractual clauses. If you reside in the EEA or other regions with laws governing data collection and use, please note that you are agreeing to the transfer of your personal data to the countries in which we operate. By providing your personal data, you consent to any transfer and processing in accordance with this Policy. We will not transfer your personal information to an overseas recipient.</p></li>
                                <li><h3>6.HOW LONG DO WE KEEP YOUR INFORMATION?</h3><p>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy policy unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</p></li>
                                <li><h3>HOW DO WE KEEP YOUR INFORMATION SAFE?</h3><p>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, the transmission of personal information to and from our Website and Mobile Application is at your own risk. You should only access the services within a secure environment.</p></li>
                                <li><h3>DO WE COLLECT INFORMATION FROM MINORS?</h3><p>We do not knowingly solicit data from or market to children under 16 years of age. By using the Website and Mobile Application, you represent that you are at least 16 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Website and Mobile Application. If we learn that personal information from users less than 16 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we have collected from children under the age of 16, please contact us at <strong> info@dentalcam.app</strong>.</p></li>
                                <li><h3>WHAT ARE YOUR PRIVACY RIGHTS?</h3><p>Personal Information</p><p>You may at any time review or change the information in your account or terminate your account by:</p><p>Contacting us using the contact information provided below</p><p>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use, and/or comply with legal requirements.</p><p><strong>Cookies and similar technologies: </strong>Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Website and Mobile Application.</p></li>
                                <li><h3>DO WE MAKE UPDATES TO THIS POLICY?</h3><p>We may update this privacy policy from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy policy, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy policy frequently to be informed of how we are protecting your information.</p></li>
                                <li><h3>HOW CAN YOU CONTACT US ABOUT THIS POLICY?</h3><p>If you have questions or comments about this policy, email us at <strong> info@dentalcam.app</strong> or, you may fill out the contact form available on the Website.</p></li>


                            </ol>
                        </Box>
                        <Box sx={{ display: 'flex', marginTop: '10px', marginRight: '20px', }}>
                            <Termlang />
                        </Box>


                    </Box>
                </Box>
            </Termstyle>
            <Footer />
        </>
    )
}

export default Privacy